-- ~/code/game/box/constants.lua

return {
    -- Spawner
    MIN_SPAWN_VELOCITY = -1,
    MAX_SPAWN_VELOCITY = 1,

    DEFAULT_BOX_SPAWN_COOLDOWN = 1.4,
    DEFAULT_BOX_SPAWN_TIER = 1,

    -- Play Area
    AREA_WIDTH = 550,
    AREA_HEIGHT = 600,

    -- Physics
    FREE_ROTATION_VELOCITY_DIVISOR = 3.5,
    ELASTICITY = 0.8,
    FRICTION = 0.0016,
    BASE_WEIGHT = 60,

    -- Dragging
    DRAG_ROTATION_MULTIPLIER = 5,
    DRAG_VELOCITY_MULTIPLIER = 0.05,
    DRAGGING_MAX_TILT = 90,
    BASE_DRAGGING_TILT_SPEED = 1,
    DRAGGED_BOX_ALPHA = 0.8,
    MAX_DRAG_VELOCITY = math.huge,

    -- Merge
    BASE_MERGE_SPEED = 400,
    BASE_MERGE_RANGE = 150,
    VELOCITY_MERGE_DURATION_FACTOR = .35,

    -- Animation
    SPAWN_SCALE_MULTIPLIER = 1.25,
    BASE_SCALE_TWEEN_DURATION = 0.3,
    WEIGHT_ANIM_DURATION_DIVISOR = 100,

    -- Object
    BASE_BOX_ZINDEX = 2
}
