-- ~/code/game/shop/constants.lua

return {
    UPGRADE_SHOP_UNLOCK_REQUIREMENT = 5,
    BLACK_MARKET_UNLOCK_REQUIREMENT = 10,
    SACRIFICE_UNLOCK_REQUIREMENT = 15,
    CATNIP_UNLOCK_REQUIREMENT = 25
}