-- ~/code/game/ui/constants.lua

local CONSTANTS = {}

-- SCREEN
CONSTANTS.CENTER_X = _G.WINDOW_WIDTH / 2
CONSTANTS.CENTER_Y = _G.WINDOW_HEIGHT / 2

-- BUTTONS
CONSTANTS.DEFAULT_BUTTON_PATH = "assets/sprites/ui/button220x75.png"

-- FONTS
CONSTANTS.STANBERRY_FONT_PATH = "assets/fonts/Stanberry.ttf"

-- TIMERS
CONSTANTS.RESET_BUTTON_WARN_TIME_OUT = 0.5

-- COMMON SCALES
CONSTANTS.ICON_SMALL_SCALE = 0.6
CONSTANTS.ICON_MEDIUM_SCALE = 0.75
CONSTANTS.SPRITE_DEFAULT_SCALE = 1
CONSTANTS.SPRITE_LARGE_SCALE = 2

-- COMMON SPACING
CONSTANTS.BUTTON_HORIZONTAL_GAP = 75
CONSTANTS.BUTTON_VERTICAL_GAP = 100
CONSTANTS.SMALL_PADDING = 5
CONSTANTS.MEDIUM_PADDING = 10
CONSTANTS.LARGE_PADDING = 25
CONSTANTS.EDGE_MARGIN = 35

-- TEXT SIZES
CONSTANTS.FONT_SMALL = 20
CONSTANTS.FONT_MEDIUM = 22
CONSTANTS.FONT_LARGE = 28

-- Z INDEX
CONSTANTS.Z_BACKGROUND = 1
CONSTANTS.Z_WORLD = 100
CONSTANTS.Z_UI_BACKGROUND = 1000
CONSTANTS.Z_UI_BUTTON = 1001
CONSTANTS.Z_UI_TEXT = 1002
CONSTANTS.Z_UI_OVERLAY = 2000

-- COMMON COLORS
CONSTANTS.COLOR_WHITE = {255, 255, 255}
CONSTANTS.COLOR_RED = {204, 49, 61}
CONSTANTS.COLOR_GREEN = {151, 188, 98}
CONSTANTS.COLOR_YELLOW = {255, 200, 0}
CONSTANTS.COLOR_BLUE = {110, 153, 202}
CONSTANTS.COLOR_GOLD = {248, 217, 109}
CONSTANTS.COLOR_DARK = {42, 42, 42}
CONSTANTS.COLOR_GRAY = {117, 124, 136}
CONSTANTS.COLOR_PURPLE = {123,104,238}

return CONSTANTS