-- ~/code/game/ui/constants.lua

local CONSTANTS = {}

-- SCREEN
CONSTANTS.CENTER_X = RESOLUTION_WIDTH / 2
CONSTANTS.CENTER_Y = RESOLUTION_HEIGHT / 2

-- BUTTONS
CONSTANTS.DEFAULT_BUTTON_PATH = "assets/sprites/ui/buttons/button220x75.png"

CONSTANTS.BOOLEAN_TOGGLE_OFF_BUTTON_PATH = "assets/sprites/ui/buttons/button74x74.png"
CONSTANTS.BOOLEAN_TOGGLE_ON_BUTTON_PATH = "assets/sprites/ui/buttons/buttoncheck74x74.png"

CONSTANTS.NUMBER_DECREASE_BUTTON_PATH = "assets/sprites/ui/buttons/buttonminus74x74.png"
CONSTANTS.NUMBER_INCREASE_BUTTON_PATH = "assets/sprites/ui/buttons/buttonplus74x74.png"

CONSTANTS.ENUM_DECREASE_BUTTON_PATH = "assets/sprites/ui/buttons/buttonarrowl74x74.png"
CONSTANTS.ENUM_INCREASE_BUTTON_PATH = "assets/sprites/ui/buttons/buttonarrowr74x74.png"

-- FONTS
CONSTANTS.STANBERRY_FONT_PATH = "assets/fonts/Stanberry.ttf"

-- INTERVALS
CONSTANTS.RESET_BUTTON_WARN_TIME_OUT = 0.5

-- INCREMENTS
CONSTANTS.NUMBER_SETTING_CHANGE_INCREMENT = .1

-- COMMON SCALES
CONSTANTS.ICON_SMALL_SCALE = 0.6
CONSTANTS.ICON_MEDIUM_SCALE = 0.75
CONSTANTS.SPRITE_DEFAULT_SCALE = 1
CONSTANTS.SPRITE_LARGE_SCALE = 2
CONSTANTS.SPRITE_HUGE_SCALE = 2.5

-- COMMON SPACING
CONSTANTS.BUTTON_HORIZONTAL_GAP = 75
CONSTANTS.BUTTON_VERTICAL_GAP = 100
CONSTANTS.SMALL_PADDING = 5
CONSTANTS.MEDIUM_PADDING = 10
CONSTANTS.LARGE_PADDING = 25
CONSTANTS.MASSIVE_PADDING = 50
CONSTANTS.EDGE_MARGIN = 35
CONSTANTS.CURRENCY_LABEL_ROW_SPACING_MULTIPLIER = 1.75

-- TEXT SIZES
CONSTANTS.FONT_SMALL = 20
CONSTANTS.FONT_MEDIUM = 22
CONSTANTS.FONT_LARGE = 28

-- Z INDEX
CONSTANTS.Z_BACKGROUND = 1
CONSTANTS.Z_WORLD = 100
CONSTANTS.Z_UI_BACKGROUND = 1000
CONSTANTS.Z_UI_BUTTON = 1001
CONSTANTS.Z_UI_TEXT = 1002
CONSTANTS.Z_UI_TEXT_OVERLAY = CONSTANTS.Z_UI_TEXT + 1
CONSTANTS.Z_UI_ICON_OVERLAY = CONSTANTS.Z_UI_TEXT + 2
CONSTANTS.Z_UI_OVERLAY = 2000

-- OPACITIES
CONSTANTS.HIGH_ALPHA = 0.75
CONSTANTS.HALF_ALPHA = 0.5
CONSTANTS.LOW_ALPHA = 0.25

-- COMMON COLORS
CONSTANTS.COLOR_WHITE = {255, 255, 255}
CONSTANTS.COLOR_RED = {204, 49, 61}
CONSTANTS.COLOR_GREEN = {151, 188, 98}
CONSTANTS.COLOR_YELLOW = {255, 200, 0}
CONSTANTS.COLOR_BLUE = {110, 153, 202}
CONSTANTS.COLOR_GOLD = {248, 217, 109}
CONSTANTS.COLOR_DARK = {42, 42, 42}
CONSTANTS.COLOR_GRAY = {117, 124, 136}
CONSTANTS.COLOR_PURPLE = {123,104,238}
CONSTANTS.INVISIBLE_COLOR = {0,0,0,0}

-- DIALOGUE
CONSTANTS.DIALOGUE_LETTER_INTREVAL = .01

-- CURSOR
CONSTANTS.CURSOR_ROTATION_LERP_SPEED = 25
CONSTANTS.CURSOR_MAX_TILT = 25
CONSTANTS.CURSOR_TILT_MULTIPLIER = .3
CONSTANTS.CURSOR_SCALE = .75
CONSTANTS.CURSOR_Z_INDEX = 999999

CONSTANTS.CURSOR_SPRITE_PATH = "assets/sprites/ui/cursors/"
CONSTANTS.CURSOR_DEFAULT_NAME = "default"

CONSTANTS.CURSOR_CLICK_SQUASH = .9
CONSTANTS.CURSOR_CLICK_RECOVERY_DURATION = .1
CONSTANTS.CURSOR_CLICK_EASING = "easeInOutQuad"

return CONSTANTS